# Generated by Django 3.0.4 on 2020-03-23 18:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 18, 26, 34, 500613, tzinfo=utc)),
        ),
    ]
